### ISSUE TITLE
Can't follow someone on identi.ca

### ISSUE THREAD

**Issue by andybalaam** [Gargron/mastodon#138]
I may be doing something wrong - apologies if so. I can't follow someone on identi.ca.

When I type bkuhn@identi.ca into the box at the bottom click the Follow button, I see "422Remote account could not be resolved"

Let me know if I can help at all.

**Comment by Gargron** [comment]
I've tried going through the process step by step. They do have webfinger, here is output for the query <https://identi.ca/.well-known/webfinger?resource=acct:bkuhn@identi.ca>:

```json
{
    "links": [
        {
            "rel": "http://webfinger.net/rel/profile-page",
            "type": "text/html",
            "href": "https://identi.ca/bkuhn"
        },
        {
            "rel": "dialback",
            "href": "https://identi.ca/api/dialback"
        },
        {
            "href": "https://identi.ca/api/user/bkuhn/profile",
            "rel": "self"
        },
        {
            "href": "https://identi.ca/api/user/bkuhn/inbox",
            "rel": "activity-inbox"
        },
        {
            "href": "https://identi.ca/api/user/bkuhn/feed",
            "rel": "activity-outbox"
        },
        {
            "rel": "followers",
            "href": "https://identi.ca/api/user/bkuhn/followers"
        },
        {
            "rel": "following",
            "href": "https://identi.ca/api/user/bkuhn/following"
        },
        {
            "rel": "favorites",
            "href": "https://identi.ca/api/user/bkuhn/favorites"
        },
        {
            "rel": "lists",
            "href": "https://identi.ca/api/user/bkuhn/lists/person"
        }
    ]
}
```

Notably missing are a `http://schemas.google.com/g/2010#updates-from` type link and a `salmon` link. It seems like pump.io does not offer Atom feeds and a Salmon end-point and instead has its own protocols. Looks like unfortunately pump.io is closed off from us. :(

**Comment by andybalaam** [comment]
How annoying!  This looks relevant I think: https://github.com/pump-io/pump.io/issues/8

**Comment by Gargron** [comment]
I'll close this until something changes in the pump.io issue

**Comment by kwill** [comment]
I get the following error message trying to follow an identi.ca user from a Mastodon host:

```
Error: mastodon.host does not implement registration_endpoint
    at Function.<anonymous> (/opt/pump.io/lib/model/host.js:153:30)
    at next (/opt/pump.io/node_modules/step/lib/step.js:51:23)
    at Function.<anonymous> (/opt/pump.io/node_modules/webfinger/lib/webfinger.js:352:17)
    at next (/opt/pump.io/node_modules/webfinger/node_modules/step/lib/step.js:51:23)
    at Function.<anonymous> (/opt/pump.io/node_modules/webfinger/lib/webfinger.js:149:17)
    at next (/opt/pump.io/node_modules/webfinger/node_modules/step/lib/step.js:51:23)
    at Parser.<anonymous> (/opt/pump.io/node_modules/webfinger/node_modules/xml2js/lib/xml2js.js:199:18)
    at emitOne (events.js:77:13)
    at Parser.emit (events.js:169:7)
    at Object.saxParser.onclosetag (/opt/pump.io/node_modules/webfinger/node_modules/xml2js/lib/xml2js.js:183:24)
```

**Comment by kwill** [comment]
It seems the relevant pump.io issue is https://github.com/pump-io/pump.io/issues/1241
