### ISSUE TITLE
Can't use rake secret to generate Application Secrets

### ISSUE THREAD

**Issue by mcat-ee** [Gargron/mastodon#375]
When I try to run `rake secret` in the root directory (containing the RakeFile) it gives me the following error:
````
$ rake secret
rake aborted!
cannot load such file -- bundler/setup
/Users/emilio/social/mastodon/config/boot.rb:3:in `<top (required)>'
/Users/emilio/social/mastodon/config/application.rb:1:in `require_relative'
/Users/emilio/social/mastodon/config/application.rb:1:in `<top (required)>'
/Users/emilio/social/mastodon/Rakefile:4:in `<top (required)>'
(See full trace by running task with --trace)
````

Full trace version:
````
$ rake secret --trace
rake aborted!
cannot load such file -- bundler/setup
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/Users/emilio/social/mastodon/config/boot.rb:3:in `<top (required)>'
/Users/emilio/social/mastodon/config/application.rb:1:in `require_relative'
/Users/emilio/social/mastodon/config/application.rb:1:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/Users/emilio/social/mastodon/Rakefile:4:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rake/rake_module.rb:25:in `load'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rake/rake_module.rb:25:in `load_rakefile'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rake/application.rb:604:in `raw_load_rakefile'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rake/application.rb:89:in `block in load_rakefile'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rake/application.rb:160:in `standard_exception_handling'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rake/application.rb:88:in `load_rakefile'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rake/application.rb:72:in `block in run'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rake/application.rb:160:in `standard_exception_handling'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rake/application.rb:70:in `run'
/usr/bin/rake:37:in `<main>'
```

Am I missing something obvious or is the build broken?

**Comment by Gargron** [comment]
Just added this line to prevent confusion in the future: https://github.com/Gargron/mastodon/blob/master/.env.production.sample#L15
